prefix=z_

# 内容表：道具/怪物/技能/地图等
[content]
indir=.\indir
outdir=C:\godot\xiuxian\data\exportjson

# 运行参数：时间/模拟/UI/规则/平衡
[yunxing_params]
indir=.\yunxing_params
outdir=C:\godot\xiuxian\data\exportjson\yunxing_params
